### ISSUE TITLE
disable mouse mode

### ISSUE THREAD

**Issue by GoogleCodeExporter** [KytechN24/xbox360wirelesschatpad#55]
```
simply want to disable mouse mode.  the option to do that is greyed out on the 
chatpad utility.  just want the chatpad to work, xpadder has much more 
flexability and personalization options than the very rigid mouse mode that has 
been included.  a thread said the main page has a way to change mouse mode but 
i cant seem to find it. tsurcess@gmail.com

```

Original issue reported on code.google.com by `tsurc...@gmail.com` on 1 Nov 2014 at 9:51

**Comment by Aer-ink** [comment]
the combination to disable the mouse mode doesnt work but its still possible to do if you open the ".config" file with the notepad that is in the directory of the "Xbox 360 Wireless Chatpad.exe" nad changing the "ctrl1MouseMode" to "false"

**Comment by KytechN24** [comment]
The LED's that flash on the controller are the orange (must be labeled incorrectly on the main page) and green modifier keys on the chatpad, at least if you have a Microsoft-branded chatpad. You might have to make sure you are using the triggers instead of the bumpers or vice-versa when using the mouse mode shortcut. You may have to hold the combination for a few seconds.
