### ISSUE TITLE
I want to use the chatpad as a substitute to keyboard, not to play

### ISSUE THREAD

**Issue by Lauberhan** [KytechN24/xbox360wirelesschatpad#71]
I use my xbox 360 wireless controller to simulate mouse trough xpadder, and in the same way the controller simulate mouse using analogic directions, I want my chatpad simulate keyboard, I noted that all posts are focused on games, but I don't want to play games, I want to do general things, like writing texts on word office, or searching things on google with my chatpad, how I proceede?

**Comment by KytechN24** [comment]
Just install the chatpad driver using the directions on the home page. The chatpad will function like a normal keyboard and it will work with any keyboard-supported program just fine. This driver also has a mouse mode built in to it so you wouldn't need to use xpadder for mouse control, but you can still use it by disabling mouse mode in the driver if you prefer xpadder since it's still more flexible. Directions for using the driver are on the home page of this project. Feel free to post to the issues thread if you have any problems.

**Comment by Lauberhan** [comment]
Thank you, friend
